"""Inspect a `dalmax-checkpoint` (`dalmax.models.checkpoint`) without
running inference: format/version, model architecture, label space,
provenance, parameter counts, file size, and a CPU dummy-forward sanity
check.

Example
-------
    poetry run python tools/loader.py --model results/dalmax1/.../saved_model.pth

On a legacy pre-2026-08-23 checkpoint (the historical `DeepLearning.save_model`
bug, see `dalmax/models/checkpoint.py`'s module docstring), prints a clear
error explaining the file contains no weights and must be regenerated by
re-training, instead of a raw unpickling traceback.
"""

from __future__ import annotations

import argparse
import sys

import _bootstrap  # noqa: F401  (must precede the `dalmax` imports)
import torch

from dalmax.models.checkpoint import CheckpointError, describe_checkpoint, load_checkpoint


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Inspect a dalmax-checkpoint file.")
    parser.add_argument("--model", type=str, required=True, help="Path to a saved_model.pth checkpoint")
    return parser


def _format_bytes(n: int) -> str:
    size = float(n)
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024 or unit == "GB":
            return f"{size:.2f} {unit}"
        size /= 1024
    return f"{size:.2f} GB"


def _print_module_breakdown(layers: list[dict]) -> None:
    """Group per-layer param counts by top-level module name (the part of
    the state_dict key before the first '.'), e.g.
    `feature_extractor.0.weight` -> `feature_extractor`."""
    totals: dict[str, int] = {}
    for layer in layers:
        top_level = layer["name"].split(".", 1)[0]
        totals[top_level] = totals.get(top_level, 0) + layer["numel"]
    name_width = max((len(name) for name in totals), default=10)
    for name in sorted(totals, key=lambda n: -totals[n]):
        print(f"    {name.ljust(name_width)}  {totals[name]:,} params")


def main(argv: list[str] | None = None) -> None:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    try:
        info = describe_checkpoint(args.model)
    except CheckpointError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"Checkpoint: {args.model}")
    print(f"  format:        {info['format']}")
    print(f"  version:       {info['version']}")
    print(f"  file size:     {_format_bytes(info['file_size_bytes'])}")
    print()
    print(f"  model_name:    {info['model_name']}")
    print(f"  n_classes:     {info['n_classes']}")
    print(f"  class_names:   {info['class_names']}")
    print(f"  img_size:      {info['img_size']}")
    print()
    extra = info["extra"]
    if extra:
        print("  provenance (extra):")
        for key, value in extra.items():
            print(f"    {key}: {value}")
    else:
        print("  provenance (extra): (none recorded)")
    print()
    print(f"  total params:  {info['total_params']:,}")
    print("  per top-level module:")
    _print_module_breakdown(info["layers"])

    print()
    try:
        clf, meta = load_checkpoint(args.model, device="cpu")
    except CheckpointError as exc:
        print(f"error loading model for device test: {exc}", file=sys.stderr)
        sys.exit(1)

    trainable_params = sum(p.numel() for p in clf.parameters() if p.requires_grad)
    print(f"  trainable params: {trainable_params:,}")

    img_size = meta["img_size"]
    dummy_input = torch.zeros(1, 3, img_size, img_size)
    with torch.no_grad():
        output, embedding = clf(dummy_input)
    print()
    print("  device test (CPU dummy forward pass):")
    print(f"    input shape:     {tuple(dummy_input.shape)}")
    print(f"    output shape:    {tuple(output.shape)}")
    print(f"    embedding shape: {tuple(embedding.shape)}")
    print("    forward pass OK")


if __name__ == "__main__":
    main()
